### ISSUE TITLE
Source of data, images, ...

### ISSUE THREAD

**Issue by Matthias84** [CivilHub/CivilHub#12]
Hi,

I'm not sure, but maybe the current version doesn't give any hint on where it get's all the basic ressources for the services. Where does the geocoding, photos, .. come from?

**Comment by jpocentek** [comment]
I'm sorry, but I'm not sure what you mean. Geobase came from http://www.geonames.org/, photos and all graphics are uploaded either by ourselves or users. If you have staticpages on mind, then yes, there is a little mess, because graphics used there are uploded via external application - https://github.com/stefanfoulis/django-filer. Geocoding files are outside of repository, they came from geonames. I will try to update README as soon, as possible, to give such details and include those files along with description how to use them.

**Comment by Matthias84** [comment]
Hi thanks for pointing to Geonames. I wasn't sure if you might used OpenStreeMap (that has a bit more complex license).

What I refer to is for example this photo: https://civilhub.org/rostock-de/ I guess nobody uploaded it manually, and it looks professional so it's from flickr, wikicommons, ... ? IMHO we should mention the source/author?

**Comment by bartekexpose** [comment]
That image was taken from wikicommons. We are aware of the need to add attribution and we will add in in the near future. However, thank you for pointing that out.

**Comment by Matthias84** [comment]
Not a problem, just an hint to indicate the author and communities that help to offer CH this material ;-)
