### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by drewterrell29** [CivilHub/CivilHub#29]
Hello,

Some of your english translations are a little broken or slightly off from what feels natural. And there are some misspellings like on your homepage for Idea to Project, "See how to proces of building...". I would recommend something like "See what the process of building a playground looks like."   I looked at your transifex page but it looks like the English section is closed. I figure you're aware of this but would offer my help if you need it. 

Very cool idea and I hope that it all goes very well for you.

Thanks!

**Comment by bartekexpose** [comment]
Hi,

Thanks for pointing out that misspelling. I am responsible for most of what is written in English on CivilHub, however I am not a native speaker nor a true translator so it is but natural that some of my translations don't feel natural.

If you are willing to help us with these issues it would be an enormous help for us. The reason that the English section is closed is due to the fact that it is the source language and as such, cannot be edited.

I have added a translation into "ENGLISH (UNITED STATES)". If you want to help us out, you can do the corrections over there. I will upload the missing pages today. However, you can do the corrections anywhere you like, you can send me a PM, write to my e-mail address, send me a screenshot of what is wrong, we are willing to accept any form that is convenient for you.

Thanks,
Bartek Bujakowski

/edit/
I just wanted to add that making corrections in "core" and "script" files in transifex (in US English) is not a good solution, so if you have any remarks concerning the language used through the site that is used in general please submit them in any other form you find appropriate. What can be corrected in transifex are sites like "creed.html", "history-timeline.html" or "team.html" etc.
